title: Lakhsmi Bharathy KUmar
description: Passionate about Machine Learning and Data Science, with a strong interest in solving real-world problems through data-driven insights. Always exploring new models, tools, and technologies to push the boundaries of what's possible with data.
show_downloads: true
theme: jekyll-theme-dinky
